### PR TITLE
Fixes #15, Use STAT output format

### LINKED ISSUE #15: Standardize output format
Hello, would this project be interested in a PR that make output follow a standardized format, namely https://github.com/fulldecent/structured-acceptance-test

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
I apologize in advance, this is my first work in Ruby.

This standardizes the output format and updates the tests. Specifically, it moves formatting out from the library and into the end program. It uses a block to allow incremental output.

Please let me know your thought and what else I can do, if anything, to get this accepted.

**Comment by mcandre** [comment]
Could you paste an example output?

**Comment by fulldecent** [comment]
Here is the examples:

```json
{
  "statVersion": "0.4.0",
  "process": {
    "name": "Line Ending Linter",
    "version": "0.3.0",
    "description": "lili searches your source code files for strange line endings that may cause issues with software interoperability",
    "maintainer": "Andrew Pennebaker",
    "email": "andrew.pennebaker@gmail.com",
    "website": "https://github.com/mcandre/lili",
    "repeatability": "Associative"
  },
  "findings": [
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    },
    {
      "failure": true,
      "rule": "Line ending",
      "description": "A line ending other than the preferred ending was found",
      "categories": [
        "Style"
      ],
      "location": {
        "path": "code/hello.txt"
      },
      "recommendation": "Use the preferred line ending /^crlf$/"
    }
  ]
}
```

**Comment by mcandre** [comment]
Neat! Would you mind making this format a `--stat` command line flag, and defaulting to a similar, but more typical ASCII format (no braces, no indentation, no quotes, silence all output unless findings > 0)?

**Comment by fulldecent** [comment]
@ilyalyo Please implement this request

**Comment by ilyalyo** [comment]
@fulldecent STAT already implemented here.
See this PR: https://github.com/mcandre/lili/pull/20

**Pull request closed without merging**
